apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-staging

resources:
- ../../base

helmCharts:
- name: myapp
  releaseName: myapp
  valuesInline:
    replicaCount: 1
    image:
      repository: rinnguyen7117/myapp
      tag: "0.0.1"
      pullPolicy: IfNotPresent
    service:
      type: NodePort
      port: 8080
      targetPort: 8080
    env:
      STAGE: "staging"

commonLabels:
  environment: staging
