apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rinnguyen2/ops.git
    targetRevision: HEAD
    path: kustomize/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-staging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
